# Generated by Django 2.1.2 on 2018-10-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionType', models.CharField(choices=[('petition', 'Petition'), ('donation', 'Donation'), ('vote', 'Vote'), ('call', 'Call'), ('attend_an_event', 'Attend an Event'), ('other', 'Other')], default='petition', max_length=20)),
                ('actionURL', models.CharField(max_length=1000)),
                ('votes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Action')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Event')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=1000)),
                ('URL', models.CharField(max_length=1000)),
                ('eventID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Event')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
        migrations.CreateModel(
            name='SpamAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Tag', max_length=250)),
                ('event', models.ManyToManyField(to='news.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=500, null=True)),
                ('actionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Action')),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField()),
                ('actionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Action')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Event')),
            ],
        ),
        migrations.AddField(
            model_name='newstag',
            name='tagId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Tag'),
        ),
        migrations.AddField(
            model_name='eventtag',
            name='tagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtag',
            unique_together={('eventID', 'tagID')},
        ),
        migrations.AlterUniqueTogether(
            name='eventaction',
            unique_together={('eventID', 'actionID')},
        ),
    ]
