# Generated by Django 2.1.2 on 2018-11-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_action_actiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actions',
            field=models.ManyToManyField(to='news.Action'),
        ),
    ]
